In [1]:
import numpy as np

In [2]:
grades = np.random.randint(50,101,size=(10,5))

In [3]:
print(grades)

[[79 77 73 60 72]
 [98 86 59 81 99]
 [50 77 56 67 95]
 [64 57 99 82 71]
 [52 93 73 96 58]
 [64 92 99 86 87]
 [91 90 99 59 51]
 [82 76 71 63 53]
 [92 56 97 61 71]
 [64 64 57 73 61]]


In [8]:
print("Student Grades (10 students for 5 subjects) : ")
for i in range(10):
    print("Student",i,":")
    for j in range(5):
        print("\tSubject ",j+1," : ",grades[i,j])

Student Grades (10 students for 5 subjects) : 
Student 0 :
	Subject  1  :  79
	Subject  2  :  77
	Subject  3  :  73
	Subject  4  :  60
	Subject  5  :  72
Student 1 :
	Subject  1  :  98
	Subject  2  :  86
	Subject  3  :  59
	Subject  4  :  81
	Subject  5  :  99
Student 2 :
	Subject  1  :  50
	Subject  2  :  77
	Subject  3  :  56
	Subject  4  :  67
	Subject  5  :  95
Student 3 :
	Subject  1  :  64
	Subject  2  :  57
	Subject  3  :  99
	Subject  4  :  82
	Subject  5  :  71
Student 4 :
	Subject  1  :  52
	Subject  2  :  93
	Subject  3  :  73
	Subject  4  :  96
	Subject  5  :  58
Student 5 :
	Subject  1  :  64
	Subject  2  :  92
	Subject  3  :  99
	Subject  4  :  86
	Subject  5  :  87
Student 6 :
	Subject  1  :  91
	Subject  2  :  90
	Subject  3  :  99
	Subject  4  :  59
	Subject  5  :  51
Student 7 :
	Subject  1  :  82
	Subject  2  :  76
	Subject  3  :  71
	Subject  4  :  63
	Subject  5  :  53
Student 8 :
	Subject  1  :  92
	Subject  2  :  56
	Subject  3  :  97
	Subject  4  :  61
	Subject 

In [12]:
#Print the grades for first 3 students:

print("Grades for the first 3 students: \n")
print(grades[:3])

Grades for the first 3 students: 

[[79 77 73 60 72]
 [98 86 59 81 99]
 [50 77 56 67 95]]


In [14]:
#Extract the grades for subject 2(index 1)
print("All marks for subejct 2 :")
print(grades[:,1])

All marks for subejct 2 :
[77 86 77 57 93 92 90 76 56 64]


In [18]:
#Calculate average grade per student
avg_per_student = np.mean(grades, axis = 1)
for i in range(10):
    print("Average marks of Student ",i," : ",avg_per_student[i])


Average marks of Student  0  :  72.2
Average marks of Student  1  :  84.6
Average marks of Student  2  :  69.0
Average marks of Student  3  :  74.6
Average marks of Student  4  :  74.4
Average marks of Student  5  :  85.6
Average marks of Student  6  :  78.0
Average marks of Student  7  :  69.0
Average marks of Student  8  :  75.4
Average marks of Student  9  :  63.8


In [20]:
#Reshape the array to (5,10)
reshaped_grades = grades.reshape(5,10)
print("Reshaped Grades (5 X 10)")
print (reshaped_grades)

Reshaped Grades (5 X 10)
[[79 77 73 60 72 98 86 59 81 99]
 [50 77 56 67 95 64 57 99 82 71]
 [52 93 73 96 58 64 92 99 86 87]
 [91 90 99 59 51 82 76 71 63 53]
 [92 56 97 61 71 64 64 57 73 61]]


In [21]:
#Slice the last two subjects(columns 3 and 4) for the last 5 students (rows 5 to 9_)
sliced_grades = grades[5:,3:]
print(sliced_grades)

[[86 87]
 [59 51]
 [63 53]
 [61 71]
 [73 61]]


In [23]:
#Add 5 bonus point to all students in subject 3(index 2)
grades[:,2] += 

#Display updated grades
print(grades[:,2])

[ 78  64  61 104  78 104 104  76 102  62]


In [26]:
#Define weights for each subject(e.g., importance of each subject)
weights  = np.array([0.2,0.3,0.1,0.25,0.15])

#apply weights to each subject grades
weighted_grades = grades * weights

#Display original weighted grades
print("Original Grades:\n",grades,"\nWeighted Grades:\n",weighted_grades)

Original Grades:
 [[ 79  77  78  60  72]
 [ 98  86  64  81  99]
 [ 50  77  61  67  95]
 [ 64  57 104  82  71]
 [ 52  93  78  96  58]
 [ 64  92 104  86  87]
 [ 91  90 104  59  51]
 [ 82  76  76  63  53]
 [ 92  56 102  61  71]
 [ 64  64  62  73  61]] 
Weighted Grades:
 [[15.8  23.1   7.8  15.   10.8 ]
 [19.6  25.8   6.4  20.25 14.85]
 [10.   23.1   6.1  16.75 14.25]
 [12.8  17.1  10.4  20.5  10.65]
 [10.4  27.9   7.8  24.    8.7 ]
 [12.8  27.6  10.4  21.5  13.05]
 [18.2  27.   10.4  14.75  7.65]
 [16.4  22.8   7.6  15.75  7.95]
 [18.4  16.8  10.2  15.25 10.65]
 [12.8  19.2   6.2  18.25  9.15]]


In [28]:
#find students who scared above 90 in subject 1
high_scores = grades[:,0]>90
print("Students who scored above 90 in Subject 1:")
print(grades[high_scores])

Students who scored above 90 in Subject 1:
[[ 98  86  64  81  99]
 [ 91  90 104  59  51]
 [ 92  56 102  61  71]]
