In [1]:
import numpy as np

In [2]:
one_d = np.array([1,2,3,4])

In [3]:
print(one_d)

[1 2 3 4]


In [4]:
two_d = np.array([1,2,3],[3,4,5])

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [5]:
two_d = np.array([[1,2,3],[4,5,6]])

In [6]:
print(two_d)

[[1 2 3]
 [4 5 6]]


In [8]:
three_d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(three_d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [9]:
print("Element at Index in 2 in 1D : ",one_d[2])

Element at Index in 2 in 1D :  3


In [11]:
print("Slice from index at 1 to 4 in 1D array : ", one_d[1:4])

Slice from index at 1 to 4 in 1D array :  [2 3 4]


In [12]:
added = one_d + 5

In [13]:
print(added)

[6 7 8 9]


In [14]:
added_ad = two_d + 5
print(added_ad)

[[ 6  7  8]
 [ 9 10 11]]


In [15]:
multiplied = two_d * 10

In [17]:
print(multiplied)

[[10 20 30]
 [40 50 60]]


In [19]:
reshaped = np.arange(12).reshape(3,4)
print("Reshaped Array (3X4):\n", reshaped)

Reshaped Array (3X4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
#Reverse an array
arr = [1,2,34,5,6,9]
print(arr[::-1])

[9, 6, 5, 34, 2, 1]


In [21]:
arr_two = [[1,2,3,4],[5,6,7,8]]
print(arr_two[::-1])

[[5, 6, 7, 8], [1, 2, 3, 4]]


In [22]:
arr = [1,1,3,4,5,5,5,5,6,7,0,9]
unique = np.unique(arr)
print("Unique elements:", unique)

Unique elements: [0 1 3 4 5 6 7 9]


In [23]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
result = np.dot(A,B)
print("Matrix multiplication result:\n", result)

Matrix multiplication result:
 [[19 22]
 [43 50]]


In [24]:
arr = np.array([10,30,40,50,60,70])
mask = arr>25

In [25]:
print(arr)

[10 30 40 50 60 70]


In [26]:
print(mask)

[False  True  True  True  True  True]


In [27]:
print(arr[mask])

[30 40 50 60 70]


In [28]:
checkerboard = np.zeros((8,8), dtype = int)
checkerboard[1::2,::2] =1
checkerboard[::2,1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
